spring.application.name=gestor-turnos

# 1. Conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_turnos
spring.datasource.username=root
spring.datasource.password=ANTONIOm167.

# 2. Configuración de Hibernate (El traductor de Java a SQL)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update